- name: Disable nodejs module
  ansible.builtin.command: /usr/bin/dnf module disable nodejs -y

- name: Enable nodejs:20 module
  ansible.builtin.command: /usr/bin/dnf module enable nodejs:20 -y

- name: Install nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: installed

- name: Add the user 'roboshop'
  ansible.builtin.user:
    name: roboshop

- name: Create app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download and extract online content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
    dest: /app
    remote_src: yes

- name: Install catalogue packages
  community.general.npm:
    path: /app

- name: Copy user.service file
  ansible.builtin.copy:
    src: user.service
    dest: /etc/systemd/system/user.service

- name: Restart service user, in all cases, also issue daemon-reload to pick up config changes
  ansible.builtin.systemd_service:
    state: restarted
    daemon_reload: true
    name: user
