

- name: Install Python 3
  ansible.builtin.command: /usr/bin/dnf install python3 gcc python3-devel -y

- name: Add the user 'roboshop'
  ansible.builtin.user:
    name: roboshop

- name: Create app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download and extract online content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/payment-v3.zip
    dest: /app
    remote_src: yes

# Lets download the dependencies & build the application
- name: cd /app
  ansible.builtin.command: /usr/bin/cd /app

- name: install pip3
  ansible.builtin.command: /usr/bin/pip3 install -r requirements.txt

- name: Copy payment.service file
  ansible.builtin.copy:
    src: payment.service
    dest: /etc/systemd/system/payment.service

- name: Restart service shipping, in all cases, also issue daemon-reload to pick up config changes
  ansible.builtin.systemd_service:
    state: restarted
    daemon_reload: true
    name: payment

- name: Enable payment
  ansible.builtin.service:
    name: payment
    enabled: yes

- name: Start payment
  ansible.builtin.systemd_service:
    name: payment
    state: started

