- name: Install mongodb
  ansible.builtin.dnf:
    name: mysql-server
    state: installed

- name: Enable mysql
  ansible.builtin.service:
    name: mysqld
    enabled: yes

- name: Start mysql
  ansible.builtin.systemd_service:
    name: mysqld
    state: started

- name: Change the default root password in order to start using the database service
  ansible.builtin.command: /usr/bin/mysql_secure_installation --set-root-pass RoboShop@1

