- name: Disable nodejs module
  ansible.builtin.shell: dnf module disable nodejs -y

- name: Enable nodejs:20 module
  ansible.builtin.command: /usr/bin/dnf module enable nodejs:20 -y

- name: Install nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: installed

- name: Add the user 'roboshop'
  ansible.builtin.user:
    name: roboshop

- name: Create app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download and extract online content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip
    dest: /app
    remote_src: yes

- name: Install cart packages
  community.general.npm:
    path: /app

- name: Copy cart.service file
  ansible.builtin.copy:
    src: cart.service
    dest: /etc/systemd/system/cart.service

- name: Restart service cart, in all cases, also issue daemon-reload to pick up config changes
  ansible.builtin.systemd_service:
    state: restarted
    daemon_reload: true
    name: cart

- name: Enable cart
  ansible.builtin.service:
    name: cart
    enabled: yes

- name: Start cart
  ansible.builtin.systemd_service:
    name: cart
    state: started